### PR TITLE
Create data source for user and user_group

### PR DESCRIPTION
**Pull request by vincenttjia**
Created 2 data sources, one for user, one for user_group.

For organizations that might have a hybrid approach. for example user provisioning using SCIM, but group using terraform. So they won't need to import each and every user and just a data source for group assignments

```terraform
data "jumpcloud_user" "example" {
  email = "example@example.com"
}

data "jumpcloud_user_group" "example" {
  name = "Example Group"
}

resource "jumpcloud_user_group_membership" "example" {
  user_id  = data.jumpcloud_user.example.id
  group_id = data.jumpcloud_user_group.example.id
}
```

### CODE REVIEW

**Comment by vincenttjia** [comment]
Hi @rldw, sorry for the late reply. I have merge the latest `main`. Thank you.

**Comment by smokingroosters** [comment]
@rldw Any update on this? We have a very similar use case and this would be super useful for us!

**Comment by vide** [comment]
This PR would also be useful for us, as a bridge for services where we have a Terraform provider to create users in but no connection to Jumpcloud/LDAP

**Comment by rldw** [comment]
Ran the pipeline again after mergin and it worked out just fine, which seems to confirm that testing outside automatically is difficult: https://github.com/sagewave/terraform-provider-jumpcloud/actions/runs/1957764778 

Version `v0.3.0` has been published 👍 Enjoy!

https://registry.terraform.io/providers/sagewave/jumpcloud/0.3.0

**Comment by vincenttjia** [comment]
Hi @rldw. Thank you.

**Pull request merged**
